### ISSUE TITLE
IRS does not start after updating to latest reworked version

### ISSUE THREAD

**Issue by Mhowser** [cooperhammond/irs#56]
I updated IRS with `sudo pip install --upgrade irs` and ran `irs --setup`, but when I type `irs` to start the program, it seems to quit immediately with no output.

my environment is Zorin OS 15 (Ubuntu 18.04)
regular Bash shell
python 3.6
![image](https://user-images.githubusercontent.com/24195572/58549419-528a2580-81c0-11e9-945f-73179061a1fc.png)

**Comment by cooperhammond** [comment]
With this latest update, I removed the CLI. It'll be coming back soon, but it needs a redesign because the old version was impossible to add features to and maintain. Version 6.7.7 still works, but 7.0.0 is much cleaner and probably quicker for downloading. Run `irs -h` or look at the README to get an idea of what the flags can do.

**Comment by Mhowser** [comment]
Thanks for the info! I was using it on my Android phone with Termux as well.
