### ISSUE TITLE
Wrong extension given for config file in readme

### ISSUE THREAD

**Issue by xenonstride** [cooperhammond/irs#71]
In the readme it is given as the extension of config file is `.yaml` whereas the correct extension is `yml` . Please correct it.

And also is there any way I could use it on my Raspberry Pi as it is ARM architecture ? I have installed crystal from this [repo](http://public.portalier.com/raspbian/).

I am trying to compile it with your repo but it says `unsupported shard.lock It was likely generated from a newer version of shards`. My shards version is 0.8.1

Edit : Tried with your 1.0.0 branch and it compiled but if I use it, it says metadata found and after that says `There were no results for that query` and says `Unhandled exception : There was no URL found on youtube for ... `.
I'd be very happy if you could help me get your program running on the Raspberry Pi 4. Thank you

**Comment by luca-schlecker** [comment]
Hey xenonstride,

`.yaml` is in fact the correct extension for YAML. It's stated on the [official website](https://yaml.org/faq.html). `.yml` is used because people like it if the extension is three characters long. So it does not need a correction. You can point the `IRS_CONFIG_LOCATION` environment variable to any file, even one's without extension, so you are free to use `.yml`.

If you want to build IRS on your raspberry pi, follow these steps:
```bash
git clone https://github.com/cooperhammond/irs
cd irs
rm shard.lock
echo "" > src/interact/future.cr
shards build
```

With these steps, I was able to successfully build IRS on my raspberry pi.
The modification to `future.cr` is needed because the Crystal version from your repo (0.33.0) still contains `future` which was dropped in Crystal [0.35.0](https://github.com/crystal-lang/crystal/releases/tag/0.35.0).

**Comment by xenonstride** [comment]
> Hey xenonstride,
> 
> `.yaml` is in fact the correct extension for YAML. It's stated on the [official website](https://yaml.org/faq.html). `.yml` is used because people like it if the extension is three characters long. So it does not need a correction. You can point the `IRS_CONFIG_LOCATION` environment variable to any file, even one's without extension, so you are free to use `.yml`.
> 
> If you want to build IRS on your raspberry pi, follow these steps:
> 
> ```shell
> git clone https://github.com/cooperhammond/irs
> cd irs
> rm shard.lock
> echo "" > src/interact/future.cr
> shards build
> ```
> 
> With these steps, I was able to successfully build IRS on mine.
> The modification of `future.cr` is needed because the Crystal version from your repo (0.33.0) still contains `future` which was dropped in Crystal [0.35.0](https://github.com/crystal-lang/crystal/releases/tag/0.35.0).

Hey @luca-schlecker, Thank you so much for your reply.
Is there any repo where I can get the latest crystal for Raspberry Pi?

**Comment by luca-schlecker** [comment]
Hey @xenonstride,

I think there is. [Cross-compiling](https://crystal-lang.org/reference/syntax_and_semantics/cross-compilation.html) crystal programs is possible and because the crystal compiler itself is written in crystal, you could compile crystal for your raspberry pi. I tried compiling crystal from source on mine, but I ran into memory size limitations and couldn't successfully compile it. I did not try to cross-compile it myself because I was happy with the little workaround I showed you. If you need crystal on your rpi only for compiling irs, it can be done with your version of crystal.
Maybe `future.cr` should be changed to make it backwards-compatible, so it compiles on the given version without throwing an error. Seems like there wouldn't be a lot of changes needed. If you are ok with it @cooperhammond I'd create a pull request for it.

**Comment by xenonstride** [comment]
> Hey @xenonstride,
> 
> I couldn't find a repo with binaries. But I think there is a way you could build it yourself. [Cross-compiling](https://crystal-lang.org/reference/syntax_and_semantics/cross-compilation.html) crystal programs is possible and because the crystal compiler itself is written in crystal, you could compile crystal for your raspberry pi. I tried compiling crystal from source on mine, but I ran into memory size limitations and couldn't successfully compile it. I did not try to cross-compile it myself because I was happy with the little workaround I showed you. If you need crystal on your rpi only for compiling irs, it can be done with your version of crystal.
> Maybe `future.cr` should be changed to make it backwards-compatible, so it compiles on the given version without throwing an error. Seems like there wouldn't be a lot of changes needed. If you are ok with it @cooperhammond I'd create a pull request for it.

Yes. There are no other repos with binaries for crystal on armhf (RPi). Maybe make a note for people on RPi to do the steps you told me to build it.
And also I have one more problem. When I try to use IRS it stucks at converting to mp3. What can I troubleshoot?

**Comment by luca-schlecker** [comment]
My guess is that it hangs because the binaries irs downloads (`ffmpeg`, `ffprobe`, ``ffserver` and `youtube-dl`) are not built for arm. You'd have to manually copy them in the binary dir specified in your config file.

**Comment by xenonstride** [comment]
> I suspect that it hangs because the binaries irs downloads (`ffmpeg`, `ffprobe`, `ffserver` and `youtube-dl`) are not built for arm. You'd have to manually copy them to the binary dir specified in your config file.

Yeah that was the problem. Thanks for the help.

**Comment by luca-schlecker** [comment]
Glad I could help. 🚀

**Comment by xenonstride** [comment]
One more doubt, How does IRS scan youtube for a song?

**Comment by luca-schlecker** [comment]
Irs gets its videos by searching YouTube for `{title} {artist} {special}` where
 - `{title}` is the song name,
 - `{artist}` is the artist's name and
 - `{special}` are special search terms.

It then filters out videos containing bad words like `album` and prefers videos containing golden phrases like `lyrics`. You can find the complete list in `src/search/youtube.cr`. If you have and further questions, please hit me up with an email (my address is stated on my profile) because this isn't the right place for it.

**Comment by luca-schlecker** [comment]
Seems resolved, close this issue please ✔
