### ISSUE TITLE
update documentation (what search_terms: does?)

### ISSUE THREAD

**Issue by ruvido** [cooperhammond/irs#85]
Using irs (v1.4.0) on OSX . Installer complained for a missing option in the config file, that was

search_terms:

following the example found in the irs output I put 

search_terms: "lyrics"

but what it does?

This option is not described in the main page of the github repo

**Comment by cooperhammond** [comment]
I just updated the project's README to address this, sorry it wasn't on there. Essentially `search_terms` is added to the youtube search query so that the user has a bit more control over what video is automatically selected. "lyrics" is the default because I've found that Youtube is more prone to suggesting music videos than just a video with the raw audio, and a few images comprising a video is a lot smaller and easier to download than one that is constantly changing.

**Comment by ruvido** [comment]
Thanks!
